name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image:  thrift:0.12
    steps:
      - run: |
          apt update
          apt install -y git
      - uses: actions/checkout@v1 # v1 has support for git 2.17
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        env:
          SONATYPE_USER: ${{secrets.SONATYPE_USER}}
          SONATYPE_TOKEN: ${{secrets.SONATYPE_TOKEN}}
          GPG_KEY: ${{secrets.GPG_KEY}}
          GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
        with:
          arguments: check publishToSonatype closeSonatypeStagingRepository -Prelease.useLastTag=true
