name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: liberica
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew check publishToSonatype closeSonatypeStagingRepository -Prelease.useLastTag=true -s
        env:
          SONATYPE_USER: ${{secrets.SONATYPE_USER}}
          SONATYPE_TOKEN: ${{secrets.SONATYPE_TOKEN}}
          GPG_KEY: ${{secrets.GPG_KEY}}
          GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}